services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: concertu-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: concertu-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
