global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ticketing"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "queue"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
